// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TxAccount {
  final int id;
  final int account;
  final Uint8List txid;
  final int height;
  final int time;
  final double? price;
  final int? category;
  final List<TxNote> notes;
  final List<TxSpend> spends;
  final List<TxOutput> outputs;
  final List<TxMemo> memos;

  const TxAccount({
    required this.id,
    required this.account,
    required this.txid,
    required this.height,
    required this.time,
    this.price,
    this.category,
    required this.notes,
    required this.spends,
    required this.outputs,
    required this.memos,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      account.hashCode ^
      txid.hashCode ^
      height.hashCode ^
      time.hashCode ^
      price.hashCode ^
      category.hashCode ^
      notes.hashCode ^
      spends.hashCode ^
      outputs.hashCode ^
      memos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          account == other.account &&
          txid == other.txid &&
          height == other.height &&
          time == other.time &&
          price == other.price &&
          category == other.category &&
          notes == other.notes &&
          spends == other.spends &&
          outputs == other.outputs &&
          memos == other.memos;
}

class TxMemo {
  final int? note;
  final int? output;
  final int pool;
  final String? memo;

  const TxMemo({
    this.note,
    this.output,
    required this.pool,
    this.memo,
  });

  @override
  int get hashCode =>
      note.hashCode ^ output.hashCode ^ pool.hashCode ^ memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxMemo &&
          runtimeType == other.runtimeType &&
          note == other.note &&
          output == other.output &&
          pool == other.pool &&
          memo == other.memo;
}

class TxNote {
  final int id;
  final int pool;
  final int height;
  final BigInt value;
  final bool locked;

  const TxNote({
    required this.id,
    required this.pool,
    required this.height,
    required this.value,
    required this.locked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pool.hashCode ^
      height.hashCode ^
      value.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxNote &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pool == other.pool &&
          height == other.height &&
          value == other.value &&
          locked == other.locked;
}

class TxOutput {
  final int id;
  final int pool;
  final int height;
  final BigInt value;
  final String address;

  const TxOutput({
    required this.id,
    required this.pool,
    required this.height,
    required this.value,
    required this.address,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pool.hashCode ^
      height.hashCode ^
      value.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxOutput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pool == other.pool &&
          height == other.height &&
          value == other.value &&
          address == other.address;
}

class TxSpend {
  final int id;
  final int pool;
  final int height;
  final BigInt value;

  const TxSpend({
    required this.id,
    required this.pool,
    required this.height,
    required this.value,
  });

  @override
  int get hashCode =>
      id.hashCode ^ pool.hashCode ^ height.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxSpend &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pool == other.pool &&
          height == other.height &&
          value == other.value;
}
