// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Persisted quote and latest provider snapshot. Amounts are base-unit strings;
/// timestamps are Unix seconds. Listing never contacts the provider.
class SavedSwap {
  final PlatformInt64 idSwap;
  final int account;
  final String originAsset;
  final String destinationAsset;
  final String swapType;
  final String amount;
  final int slippageTolerance;
  final String recipient;
  final String refundTo;
  final String deadline;
  final String amountIn;
  final String amountOut;
  final String? minAmountIn;
  final String? minAmountOut;
  final String depositAddress;
  final String? depositMemo;
  final String? depositTxHash;
  final PlatformInt64? depositSubmittedAt;
  final String quoteResponse;
  final String? status;
  final String? statusResponse;
  final PlatformInt64? lastCheckedAt;
  final PlatformInt64? completedAt;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const SavedSwap({
    required this.idSwap,
    required this.account,
    required this.originAsset,
    required this.destinationAsset,
    required this.swapType,
    required this.amount,
    required this.slippageTolerance,
    required this.recipient,
    required this.refundTo,
    required this.deadline,
    required this.amountIn,
    required this.amountOut,
    this.minAmountIn,
    this.minAmountOut,
    required this.depositAddress,
    this.depositMemo,
    this.depositTxHash,
    this.depositSubmittedAt,
    required this.quoteResponse,
    this.status,
    this.statusResponse,
    this.lastCheckedAt,
    this.completedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      idSwap.hashCode ^
      account.hashCode ^
      originAsset.hashCode ^
      destinationAsset.hashCode ^
      swapType.hashCode ^
      amount.hashCode ^
      slippageTolerance.hashCode ^
      recipient.hashCode ^
      refundTo.hashCode ^
      deadline.hashCode ^
      amountIn.hashCode ^
      amountOut.hashCode ^
      minAmountIn.hashCode ^
      minAmountOut.hashCode ^
      depositAddress.hashCode ^
      depositMemo.hashCode ^
      depositTxHash.hashCode ^
      depositSubmittedAt.hashCode ^
      quoteResponse.hashCode ^
      status.hashCode ^
      statusResponse.hashCode ^
      lastCheckedAt.hashCode ^
      completedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedSwap &&
          runtimeType == other.runtimeType &&
          idSwap == other.idSwap &&
          account == other.account &&
          originAsset == other.originAsset &&
          destinationAsset == other.destinationAsset &&
          swapType == other.swapType &&
          amount == other.amount &&
          slippageTolerance == other.slippageTolerance &&
          recipient == other.recipient &&
          refundTo == other.refundTo &&
          deadline == other.deadline &&
          amountIn == other.amountIn &&
          amountOut == other.amountOut &&
          minAmountIn == other.minAmountIn &&
          minAmountOut == other.minAmountOut &&
          depositAddress == other.depositAddress &&
          depositMemo == other.depositMemo &&
          depositTxHash == other.depositTxHash &&
          depositSubmittedAt == other.depositSubmittedAt &&
          quoteResponse == other.quoteResponse &&
          status == other.status &&
          statusResponse == other.statusResponse &&
          lastCheckedAt == other.lastCheckedAt &&
          completedAt == other.completedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class SwapAsset {
  final String assetId;
  final int decimals;
  final String blockchain;
  final String symbol;
  final String? price;
  final String? contractAddress;

  const SwapAsset({
    required this.assetId,
    required this.decimals,
    required this.blockchain,
    required this.symbol,
    this.price,
    this.contractAddress,
  });

  @override
  int get hashCode =>
      assetId.hashCode ^
      decimals.hashCode ^
      blockchain.hashCode ^
      symbol.hashCode ^
      price.hashCode ^
      contractAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapAsset &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          decimals == other.decimals &&
          blockchain == other.blockchain &&
          symbol == other.symbol &&
          price == other.price &&
          contractAddress == other.contractAddress;
}

class SwapDetails {
  final String? amountIn;
  final String? amountOut;
  final String? refundedAmount;
  final List<SwapTransaction> originChainTxHashes;
  final List<SwapTransaction> destinationChainTxHashes;

  const SwapDetails({
    this.amountIn,
    this.amountOut,
    this.refundedAmount,
    required this.originChainTxHashes,
    required this.destinationChainTxHashes,
  });

  @override
  int get hashCode =>
      amountIn.hashCode ^
      amountOut.hashCode ^
      refundedAmount.hashCode ^
      originChainTxHashes.hashCode ^
      destinationChainTxHashes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapDetails &&
          runtimeType == other.runtimeType &&
          amountIn == other.amountIn &&
          amountOut == other.amountOut &&
          refundedAmount == other.refundedAmount &&
          originChainTxHashes == other.originChainTxHashes &&
          destinationChainTxHashes == other.destinationChainTxHashes;
}

class SwapQuote {
  final String? depositAddress;
  final String? depositMemo;
  final String amountIn;
  final String amountOut;
  final String? minAmountIn;
  final String? minAmountOut;
  final String? amountInFormatted;
  final String? amountOutFormatted;
  final String? amountInUsd;
  final String? amountOutUsd;
  final String? deadline;
  final int? timeEstimate;

  const SwapQuote({
    this.depositAddress,
    this.depositMemo,
    required this.amountIn,
    required this.amountOut,
    this.minAmountIn,
    this.minAmountOut,
    this.amountInFormatted,
    this.amountOutFormatted,
    this.amountInUsd,
    this.amountOutUsd,
    this.deadline,
    this.timeEstimate,
  });

  @override
  int get hashCode =>
      depositAddress.hashCode ^
      depositMemo.hashCode ^
      amountIn.hashCode ^
      amountOut.hashCode ^
      minAmountIn.hashCode ^
      minAmountOut.hashCode ^
      amountInFormatted.hashCode ^
      amountOutFormatted.hashCode ^
      amountInUsd.hashCode ^
      amountOutUsd.hashCode ^
      deadline.hashCode ^
      timeEstimate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapQuote &&
          runtimeType == other.runtimeType &&
          depositAddress == other.depositAddress &&
          depositMemo == other.depositMemo &&
          amountIn == other.amountIn &&
          amountOut == other.amountOut &&
          minAmountIn == other.minAmountIn &&
          minAmountOut == other.minAmountOut &&
          amountInFormatted == other.amountInFormatted &&
          amountOutFormatted == other.amountOutFormatted &&
          amountInUsd == other.amountInUsd &&
          amountOutUsd == other.amountOutUsd &&
          deadline == other.deadline &&
          timeEstimate == other.timeEstimate;
}

/// Keep the complete provider response, including its signature, for persistence.
class SwapQuoteResponse {
  final SwapQuote quote;
  final String rawResponse;

  const SwapQuoteResponse({
    required this.quote,
    required this.rawResponse,
  });

  @override
  int get hashCode => quote.hashCode ^ rawResponse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapQuoteResponse &&
          runtimeType == other.runtimeType &&
          quote == other.quote &&
          rawResponse == other.rawResponse;
}

/// Source/destination fields are shared so inbound swaps can reuse the client later.
class SwapRequest {
  final bool dry;
  final SwapType swapType;
  final String originAsset;
  final String destinationAsset;

  /// Base units of source for EXACT_INPUT, destination for EXACT_OUTPUT.
  final String amount;

  /// Basis points: 100 = 1%.
  final int slippageTolerance;
  final String recipient;
  final String refundTo;

  /// RFC 3339 expiry, validated by 1Click.
  final String deadline;

  const SwapRequest({
    required this.dry,
    required this.swapType,
    required this.originAsset,
    required this.destinationAsset,
    required this.amount,
    required this.slippageTolerance,
    required this.recipient,
    required this.refundTo,
    required this.deadline,
  });

  @override
  int get hashCode =>
      dry.hashCode ^
      swapType.hashCode ^
      originAsset.hashCode ^
      destinationAsset.hashCode ^
      amount.hashCode ^
      slippageTolerance.hashCode ^
      recipient.hashCode ^
      refundTo.hashCode ^
      deadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapRequest &&
          runtimeType == other.runtimeType &&
          dry == other.dry &&
          swapType == other.swapType &&
          originAsset == other.originAsset &&
          destinationAsset == other.destinationAsset &&
          amount == other.amount &&
          slippageTolerance == other.slippageTolerance &&
          recipient == other.recipient &&
          refundTo == other.refundTo &&
          deadline == other.deadline;
}

class SwapStatus {
  /// Preserve unknown provider states instead of reporting a false failure.
  final String status;
  final SwapDetails? swapDetails;
  final String rawResponse;

  const SwapStatus({
    required this.status,
    this.swapDetails,
    required this.rawResponse,
  });

  @override
  int get hashCode =>
      status.hashCode ^ swapDetails.hashCode ^ rawResponse.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          swapDetails == other.swapDetails &&
          rawResponse == other.rawResponse;
}

class SwapTransaction {
  final String hash;
  final String? explorerUrl;

  const SwapTransaction({
    required this.hash,
    this.explorerUrl,
  });

  @override
  int get hashCode => hash.hashCode ^ explorerUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapTransaction &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          explorerUrl == other.explorerUrl;
}

enum SwapType {
  exactInput,
  exactOutput,
  ;
}
