// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Wrapper around `openalias::CryptoAddress` with FRB-compatible field types.
/// The `additional_values` BTreeMap is converted to a Vec of pairs.
class OpenAliasAddress {
  /// The cryptocurrency identifier (e.g., "zcash", "btc", "xmr")
  final String cryptocurrency;

  /// The resolved address string
  final String address;

  /// Optional human-readable recipient name
  final String? recipientName;

  /// Optional transaction description
  final String? txDescription;

  /// Optional transaction amount
  final String? txAmount;

  /// Optional transaction payment ID
  final String? txPaymentId;

  /// Optional address signature
  final String? addressSignature;

  /// Checksum info: (crc32, verified_ok)
  final (int, bool)? checksum;

  /// Additional non-standard key-value pairs
  final List<(String, String)> additionalValues;

  const OpenAliasAddress({
    required this.cryptocurrency,
    required this.address,
    this.recipientName,
    this.txDescription,
    this.txAmount,
    this.txPaymentId,
    this.addressSignature,
    this.checksum,
    required this.additionalValues,
  });

  @override
  int get hashCode =>
      cryptocurrency.hashCode ^
      address.hashCode ^
      recipientName.hashCode ^
      txDescription.hashCode ^
      txAmount.hashCode ^
      txPaymentId.hashCode ^
      addressSignature.hashCode ^
      checksum.hashCode ^
      additionalValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenAliasAddress &&
          runtimeType == other.runtimeType &&
          cryptocurrency == other.cryptocurrency &&
          address == other.address &&
          recipientName == other.recipientName &&
          txDescription == other.txDescription &&
          txAmount == other.txAmount &&
          txPaymentId == other.txPaymentId &&
          addressSignature == other.addressSignature &&
          checksum == other.checksum &&
          additionalValues == other.additionalValues;
}
