// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TxOut {
  final TransparentAddress? address;
  final BigInt value;
  final int vout;

  const TxOut({
    this.address,
    required this.value,
    required this.vout,
  });

  @override
  int get hashCode => address.hashCode ^ value.hashCode ^ vout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxOut &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          value == other.value &&
          vout == other.vout;
}
