// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PcztPackage {
  final Uint8List pczt;
  final UsizeArray3 nSpends;
  final Uint64List saplingIndices;
  final Uint64List orchardIndices;
  final bool canSign;

  const PcztPackage({
    required this.pczt,
    required this.nSpends,
    required this.saplingIndices,
    required this.orchardIndices,
    required this.canSign,
  });

  @override
  int get hashCode =>
      pczt.hashCode ^
      nSpends.hashCode ^
      saplingIndices.hashCode ^
      orchardIndices.hashCode ^
      canSign.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PcztPackage &&
          runtimeType == other.runtimeType &&
          pczt == other.pczt &&
          nSpends == other.nSpends &&
          saplingIndices == other.saplingIndices &&
          orchardIndices == other.orchardIndices &&
          canSign == other.canSign;
}
