name: "Build Zebra & Zaino"
inputs:
  MINER_SEED:
    required: true
  MINER_ADDRESS:
    required: true
  SEED:
    required: true
  DESTINATION_ADDRESS:
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache zebra
      id: cache-zebra
      uses: actions/cache@v4
      with:
        path: |
          ./tools/bin
        key: ${{ runner.os }}-zebra-4.2.0

    - name: Install zkool
      if: github.repository != 'hhanh00/zkool2' && steps.cache-zebra.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cargo install --git https://github.com/hhanh00/zkool2 --features=graphql --root ./tools --bin zkool_graphql
        curl -sf --create-dirs https://raw.githubusercontent.com/hhanh00/zkool2/refs/heads/main/misc/zebra.toml misc/zebra.toml

    - name: Install zebra & zaino
      if: steps.cache-zebra.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt update && sudo apt install -y libclang-dev clang

        cargo install --git https://github.com/ZcashFoundation/zebra --tag v4.2.0 --features=internal-miner --root ./tools zebrad
        cargo install --git https://github.com/zingolabs/zaino --tag 0.2.0-rc.6 --root ./tools zainod

    - name: Save cache
      if: steps.cache-zebra.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ./tools/bin
        key: ${{ runner.os }}-zebra-4.2.0

    - name: Install config
      if: github.repository != 'hhanh00/zkool2'
      shell: bash
      run: |
        curl -sf --create-dirs https://raw.githubusercontent.com/hhanh00/zkool2/refs/heads/main/misc/zebra.toml -o misc/zebra.toml
        curl -sf https://raw.githubusercontent.com/hhanh00/zkool2/refs/heads/wip/example/sh/mine.sh -o mine.sh
        chmod +x mine.sh

    - name: Add tools to PATH
      shell: bash
      run: echo "$GITHUB_WORKSPACE/tools/bin" >> $GITHUB_PATH

    - name: Start regtest, mine and shield to wallet
      shell: bash
      run: ./mine.sh
      env:
        MINER_SEED: ${{ inputs.MINER_SEED }}
        MINER_ADDRESS: ${{ inputs.MINER_ADDRESS }}
        SEED: ${{ inputs.SEED }}
        DESTINATION_ADDRESS: ${{ inputs.DESTINATION_ADDRESS }}
