// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Offline address validation for a specified blockchain. Ethereum validation
/// checks hex syntax only; this revision does not enforce EIP-55 checksums.
bool validateBlockchainAddress(
        {required String address, required String blockchain}) =>
    RustLib.instance.api.crateApiAddressValidateBlockchainAddress(
        address: address, blockchain: blockchain);
