// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<DbAccountPreview>> listDbAccounts({required String dbFilepath}) =>
    RustLib.instance.api.crateApiDbListDbAccounts(dbFilepath: dbFilepath);

Future<void> changeDbPassword(
        {required String dbFilepath,
        required String tmpDir,
        required String oldPassword,
        required String newPassword}) =>
    RustLib.instance.api.crateApiDbChangeDbPassword(
        dbFilepath: dbFilepath,
        tmpDir: tmpDir,
        oldPassword: oldPassword,
        newPassword: newPassword);

Future<String?> getProp({required String key, required Coin c}) =>
    RustLib.instance.api.crateApiDbGetProp(key: key, c: c);

Future<void> putProp(
        {required String key, required String value, required Coin c}) =>
    RustLib.instance.api.crateApiDbPutProp(key: key, value: value, c: c);

/// Deletes a wallet database and every file that belongs to it.
///
/// The wallet file must exist; everything beside it is optional. The voting
/// sidecar is one of those files, and leaving it behind would strand voting
/// state that a wallet later recreated under the same name would inherit. The
/// WAL companions of both only exist after an unclean shutdown.
Future<void> deleteDb({required String dbFilepath}) =>
    RustLib.instance.api.crateApiDbDeleteDb(dbFilepath: dbFilepath);

/// Renames a wallet database and every file that belongs to it.
///
/// Refuses an existing destination: `fs::rename` overwrites silently, and the
/// destination here is another wallet. The voting sidecar moves with the
/// wallet so its state stays attached to the wallet it describes, and the WAL
/// companions move too -- one left behind holds commits the renamed database
/// would no longer see.
Future<void> renameDb(
        {required String dbFilepath, required String newDbFilepath}) =>
    RustLib.instance.api.crateApiDbRenameDb(
        dbFilepath: dbFilepath, newDbFilepath: newDbFilepath);

Future<List<String>> listDbNames({required String dir}) =>
    RustLib.instance.api.crateApiDbListDbNames(dir: dir);

class DbAccountPreview {
  final int id;
  final String name;

  const DbAccountPreview({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbAccountPreview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
