// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Issue a new ZSA (Zcash Shielded Asset) via the PCZT workflow.
///
/// This creates, signs, and extracts a full issuance transaction. The issuance
/// key is derived from the wallet's BIP-39 seed (ZIP-32 purpose 227).
///
/// # Parameters
/// - `asset_name`: Human-readable asset description (e.g. "WETH"). Must be non-empty UTF-8.
/// - `amount`: Raw units to issue (passed to `NoteValue::from_raw`).
/// - `first_issuance`: Whether this is the first issuance of this asset — adds a zero-value
///   reference note per ZIP-227.
/// - `finalize`: Whether to finalize the asset, preventing any future issuance of this type.
/// - `c`: Wallet state.
///
/// # Returns
/// Serialized transaction bytes, ready for broadcast via `api::pay::broadcast_transaction`.
Future<Uint8List> issueAsset(
        {required String assetName,
        required BigInt amount,
        required bool firstIssuance,
        required bool finalize,
        required int idAccount,
        required Coin c}) =>
    RustLib.instance.api.crateApiIssuanceIssueAsset(
        assetName: assetName,
        amount: amount,
        firstIssuance: firstIssuance,
        finalize: finalize,
        idAccount: idAccount,
        c: c);
