// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

bool isValidPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiKeyIsValidPhrase(phrase: phrase);

bool isValidFvk({required String fvk}) =>
    RustLib.instance.api.crateApiKeyIsValidFvk(fvk: fvk);

bool isValidKey({required String key}) =>
    RustLib.instance.api.crateApiKeyIsValidKey(key: key);

bool isValidAddress({required String address}) =>
    RustLib.instance.api.crateApiKeyIsValidAddress(address: address);

bool isValidTransparentAddress({required String address}) =>
    RustLib.instance.api.crateApiKeyIsValidTransparentAddress(address: address);

bool isTexAddress({required String address}) =>
    RustLib.instance.api.crateApiKeyIsTexAddress(address: address);

int getKeyPools({required String key}) =>
    RustLib.instance.api.crateApiKeyGetKeyPools(key: key);
