// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pay.dart';

// These functions are ignored because they are not marked as `pub`: `get_hw_fvk`, `get_hw_next_diversifier_address`, `get_hw_sapling_address`, `get_hw_transparent_address`, `show_sapling_address`, `show_transparent_address`

Stream<SigningEvent> signLedgerTransaction(
        {required PcztPackage package, required Coin c}) =>
    RustLib.instance.api
        .crateApiLedgerSignLedgerTransaction(package: package, c: c);
