// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mempool.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `run_mempool`

Future<Uint8List> getMempoolTx({required String txId}) =>
    RustLib.instance.api.crateApiMempoolGetMempoolTx(txId: txId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Mempool>>
abstract class Mempool implements RustOpaqueInterface {
  Future<void> cancel();

  factory Mempool() => RustLib.instance.api.crateApiMempoolMempoolNew();

  Stream<MempoolMsg> run({required int height});
}

@freezed
sealed class MempoolMsg with _$MempoolMsg {
  const MempoolMsg._();

  const factory MempoolMsg.txId(
    String field0,
    List<(int, String, PlatformInt64)> field1,
    int field2,
  ) = MempoolMsg_TxId;
}
