// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mempool.freezed.dart';

Stream<MempoolMsg> runMempool({required int height}) =>
    RustLib.instance.api.crateApiMempoolRunMempool(height: height);

@freezed
sealed class MempoolMsg with _$MempoolMsg {
  const MempoolMsg._();

  const factory MempoolMsg.txId(
    String field0,
  ) = MempoolMsg_TxId;
}
