// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'migrate.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Run one migration step. Fully idempotent — re-scans notes on every call.
/// The caller should poll this periodically (e.g., every 6 seconds).
Future<MigrationEvent> stepMigration({required Coin c}) =>
    RustLib.instance.api.crateApiMigrateStepMigration(c: c);

/// Get current migration status for the UI.
/// Returns phase, progress, and work breakdown based on current note state.
Future<MigrationStatus> getMigrationStatus({required Coin c}) =>
    RustLib.instance.api.crateApiMigrateGetMigrationStatus(c: c);

@freezed
sealed class MigrationEvent with _$MigrationEvent {
  const MigrationEvent._();

  /// A split transaction was broadcast.
  const factory MigrationEvent.splitComplete({
    required BigInt fee,
  }) = MigrationEvent_SplitComplete;

  /// A migration transaction was broadcast.
  const factory MigrationEvent.migrateComplete({
    required BigInt fee,
  }) = MigrationEvent_MigrateComplete;

  /// Migration is complete.
  const factory MigrationEvent.complete() = MigrationEvent_Complete;

  /// No action needed (idempotent — call again later).
  const factory MigrationEvent.nothingToDo() = MigrationEvent_NothingToDo;

  /// An error occurred.
  const factory MigrationEvent.error({
    required String message,
  }) = MigrationEvent_Error;
}

/// Current migration status for the UI.
class MigrationStatus {
  final String phase;
  final double progress;
  final String nextAction;
  final String workSummary;
  final int sdNotesCount;
  final int nonSdNotesCount;

  const MigrationStatus({
    required this.phase,
    required this.progress,
    required this.nextAction,
    required this.workSummary,
    required this.sdNotesCount,
    required this.nonSdNotesCount,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      progress.hashCode ^
      nextAction.hashCode ^
      workSummary.hashCode ^
      sdNotesCount.hashCode ^
      nonSdNotesCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationStatus &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          progress == other.progress &&
          nextAction == other.nextAction &&
          workSummary == other.workSummary &&
          sdNotesCount == other.sdNotesCount &&
          nonSdNotesCount == other.nonSdNotesCount;
}
