// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../near_intents.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<SavedSwap>> nearIntentsListSwaps(
        {required bool pendingOnly, required Coin c}) =>
    RustLib.instance.api.crateApiNearIntentsNearIntentsListSwaps(
        pendingOnly: pendingOnly, c: c);

Future<List<SwapAsset>> nearIntentsAssets({required Coin c}) =>
    RustLib.instance.api.crateApiNearIntentsNearIntentsAssets(c: c);

Future<SwapQuoteResponse> nearIntentsQuote(
        {required SwapRequest request, required Coin c}) =>
    RustLib.instance.api
        .crateApiNearIntentsNearIntentsQuote(request: request, c: c);

Future<SwapStatus> nearIntentsStatus(
        {required String depositAddress,
        String? depositMemo,
        required Coin c}) =>
    RustLib.instance.api.crateApiNearIntentsNearIntentsStatus(
        depositAddress: depositAddress, depositMemo: depositMemo, c: c);

Future<SwapStatus> nearIntentsRefreshSwapStatus(
        {required PlatformInt64 idSwap, required Coin c}) =>
    RustLib.instance.api
        .crateApiNearIntentsNearIntentsRefreshSwapStatus(idSwap: idSwap, c: c);

Future<void> nearIntentsSubmitDeposit(
        {required String depositAddress,
        required String txHash,
        required Coin c}) =>
    RustLib.instance.api.crateApiNearIntentsNearIntentsSubmitDeposit(
        depositAddress: depositAddress, txHash: txHash, c: c);
