// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Usd`, `ZcashUSD`

Future<void> initDatadir({required String directory}) =>
    RustLib.instance.api.crateApiNetworkInitDatadir(directory: directory);

Future<int> getCurrentHeight({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetCurrentHeight(c: c);

Future<double> getCoingeckoPrice() =>
    RustLib.instance.api.crateApiNetworkGetCoingeckoPrice();

Future<String> getNetworkName({required Coin c}) =>
    RustLib.instance.api.crateApiNetworkGetNetworkName(c: c);
