// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../coin.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `USD`, `ZcashUSD`

void setLwd({required ServerType serverType, required String lwd}) =>
    RustLib.instance.api
        .crateApiNetworkSetLwd(serverType: serverType, lwd: lwd);

Future<int> getCurrentHeight() =>
    RustLib.instance.api.crateApiNetworkGetCurrentHeight();

Future<double> getCoingeckoPrice() =>
    RustLib.instance.api.crateApiNetworkGetCoingeckoPrice();
