// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../pay.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resolve an OpenAlias name and return Zcash [`Recipient`]s valid for
/// the wallet's network.
///
/// Performs DNS TXT lookup, parses OA1 records, filters for Zcash
/// addresses, and validates them against the wallet's network type.
Future<List<Recipient>> resolveOpenalias(
        {required String alias, required Coin c}) =>
    RustLib.instance.api.crateApiOpenaliasResolveOpenalias(alias: alias, c: c);

/// Resolve an OpenAlias name and return ALL cryptocurrency addresses
/// found (not just Zcash) as [`Recipient`]s.
Future<List<Recipient>> resolveOpenaliasAll({required String alias}) =>
    RustLib.instance.api.crateApiOpenaliasResolveOpenaliasAll(alias: alias);

/// Validate whether a string looks like a valid OpenAlias name format.
/// Returns true/false without performing any DNS lookup.
bool validateOpenaliasName({required String alias}) =>
    RustLib.instance.api.crateApiOpenaliasValidateOpenaliasName(alias: alias);

/// Validate that an address string is a syntactically valid Zcash address
/// for the wallet's network (convenience wrapper returning bool).
///
/// See [`try_validate_zcash_address`] for the `Result`-returning variant
/// that provides error details.
bool validateZcashAddress({required String address, required Coin c}) =>
    RustLib.instance.api
        .crateApiOpenaliasValidateZcashAddress(address: address, c: c);

/// Try to validate that an address string is a syntactically valid Zcash
/// address for the wallet's network, returning `Ok(())` or an error with
/// details about why validation failed.
void tryValidateZcashAddress({required String address, required Coin c}) =>
    RustLib.instance.api
        .crateApiOpenaliasTryValidateZcashAddress(address: address, c: c);

/// Get the raw OpenAlias TXT record strings for diagnostic purposes.
Future<List<String>> resolveOpenaliasRaw({required String alias}) =>
    RustLib.instance.api.crateApiOpenaliasResolveOpenaliasRaw(alias: alias);
