// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../pay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pay.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `borrow_decode`, `decode`, `encode`

Future<PcztPackage> prepare(
        {required int srcPools,
        required List<Recipient> recipients,
        required bool recipientPaysFee}) =>
    RustLib.instance.api.crateApiPayPrepare(
        srcPools: srcPools,
        recipients: recipients,
        recipientPaysFee: recipientPaysFee);

Future<PcztPackage> signTransaction({required PcztPackage pczt}) =>
    RustLib.instance.api.crateApiPaySignTransaction(pczt: pczt);

Future<Uint8List> extractTransaction({required PcztPackage package}) =>
    RustLib.instance.api.crateApiPayExtractTransaction(package: package);

Future<Uint8List> packTransaction({required PcztPackage pczt}) =>
    RustLib.instance.api.crateApiPayPackTransaction(pczt: pczt);

Future<PcztPackage> unpackTransaction({required List<int> bytes}) =>
    RustLib.instance.api.crateApiPayUnpackTransaction(bytes: bytes);

Future<String> broadcastTransaction(
        {required int height, required List<int> txBytes}) =>
    RustLib.instance.api
        .crateApiPayBroadcastTransaction(height: height, txBytes: txBytes);

TxPlan toPlan({required PcztPackage package}) =>
    RustLib.instance.api.crateApiPayToPlan(package: package);

Future<String> send({required int height, required List<int> data}) =>
    RustLib.instance.api.crateApiPaySend(height: height, data: data);

List<Recipient>? parsePaymentUri({required String uri}) =>
    RustLib.instance.api.crateApiPayParsePaymentUri(uri: uri);

@freezed
class PcztPackage with _$PcztPackage {
  const factory PcztPackage({
    required Uint8List pczt,
    required UsizeArray3 nSpends,
    required Uint64List saplingIndices,
    required Uint64List orchardIndices,
    required bool canSign,
    required bool canBroadcast,
    required String puri,
  }) = _PcztPackage;
}
