// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Check whether Sapling parameters are already on disk.
SaplingParamsStatus checkSaplingParams() =>
    RustLib.instance.api.crateApiSaplingCheckSaplingParams();

/// Download Sapling parameters from the z.cash download server.
/// Verifies file size and hash upon download.
/// Safe to call even if they are already downloaded (no-op if valid).
Future<void> downloadSaplingParams() =>
    RustLib.instance.api.crateApiSaplingDownloadSaplingParams();

/// Status of the Sapling proving parameters on disk.
class SaplingParamsStatus {
  final bool downloaded;

  const SaplingParamsStatus({
    required this.downloaded,
  });

  @override
  int get hashCode => downloaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaplingParamsStatus &&
          runtimeType == other.runtimeType &&
          downloaded == other.downloaded;
}
