// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String newSeed({required String phrase}) =>
    RustLib.instance.api.crateApiSimpleNewSeed(phrase: phrase);

int storeAccountMetadata(
        {required int coin,
        required String name,
        Uint8List? icon,
        required int birth,
        required int height}) =>
    RustLib.instance.api.crateApiSimpleStoreAccountMetadata(
        coin: coin, name: name, icon: icon, birth: birth, height: height);

Future<int> storeAccountSeed(
        {required int coin,
        required int id,
        required String phrase,
        required int aindex}) =>
    RustLib.instance.api.crateApiSimpleStoreAccountSeed(
        coin: coin, id: id, phrase: phrase, aindex: aindex);

void setDbFilepath({required int coin, required String dbFilepath}) =>
    RustLib.instance.api
        .crateApiSimpleSetDbFilepath(coin: coin, dbFilepath: dbFilepath);
