// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../sync.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_account_birth_height`, `get_transparent_addresses`

Future<List<Transaction>> getTransparentTransactions(
        {required List<int> accounts}) =>
    RustLib.instance.api
        .crateApiSyncGetTransparentTransactions(accounts: accounts);
