// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> fillMissingTxPrices() =>
    RustLib.instance.api.crateApiTransactionFillMissingTxPrices();

Future<void> setTxCategory({required int id, int? category}) =>
    RustLib.instance.api
        .crateApiTransactionSetTxCategory(id: id, category: category);

Future<List<(String, double, bool)>> fetchCategoryAmounts(
        {int? from, int? to}) =>
    RustLib.instance.api
        .crateApiTransactionFetchCategoryAmounts(from: from, to: to);

Future<List<(int, double)>> fetchAmounts(
        {int? from, int? to, required int category}) =>
    RustLib.instance.api.crateApiTransactionFetchAmounts(
        from: from, to: to, category: category);
