// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<DartVault> initVault(
        {required FutureOr<void> Function(Uint8List) append,
        required FutureOr<Uint8List> Function() readLog}) =>
    RustLib.instance.api
        .crateApiVaultInitVault(append: append, readLog: readLog);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartVault>>
abstract class DartVault implements RustOpaqueInterface {
  Future<Uint8List> setMasterPassword(
      {String? oldPassword, required String newPassword, Uint8List? oldBytes});

  Future<void> storeAccount(
      {required String name,
      required String seed,
      required int aindex,
      required bool useInternal,
      required int birthHeight,
      required List<int> pk});

  Future<void> test();
}
