// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'vote.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `connect_voted`

Future<String> compileElectionDef(
        {required String electionJson, required String seed}) =>
    RustLib.instance.api
        .crateApiVoteCompileElectionDef(electionJson: electionJson, seed: seed);

Future<ElectionPropsPub> parseElection({required String electionJson}) =>
    RustLib.instance.api.crateApiVoteParseElection(electionJson: electionJson);

Future<ElectionId> getElectionId({required Coin c}) =>
    RustLib.instance.api.crateApiVoteGetElectionId(c: c);

Future<ElectionPropsPub> getElection({required Coin c}) =>
    RustLib.instance.api.crateApiVoteGetElection(c: c);

Future<ElectionPropsPub> fetchElection(
        {required String url, required List<int> hash, required Coin c}) =>
    RustLib.instance.api.crateApiVoteFetchElection(url: url, hash: hash, c: c);

class ChoiceProp {
  final String? title;
  final String? subtitle;
  final List<String> answers;

  const ChoiceProp({
    this.title,
    this.subtitle,
    required this.answers,
  });

  @override
  int get hashCode => title.hashCode ^ subtitle.hashCode ^ answers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChoiceProp &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subtitle == other.subtitle &&
          answers == other.answers;
}

@freezed
sealed class ElectionId with _$ElectionId {
  const factory ElectionId({
    String? url,
    required Uint8List hash,
  }) = _ElectionId;
}

class ElectionPropsPub {
  final int start;
  final int end;
  final bool needSig;
  final String name;
  final List<QuestionPropPub> questions;

  const ElectionPropsPub({
    required this.start,
    required this.end,
    required this.needSig,
    required this.name,
    required this.questions,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      end.hashCode ^
      needSig.hashCode ^
      name.hashCode ^
      questions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ElectionPropsPub &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          needSig == other.needSig &&
          name == other.name &&
          questions == other.questions;
}

class QuestionPropPub {
  final String title;
  final String subtitle;
  final BigInt index;
  final String address;
  final List<ChoiceProp> choices;

  const QuestionPropPub({
    required this.title,
    required this.subtitle,
    required this.index,
    required this.address,
    required this.choices,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      subtitle.hashCode ^
      index.hashCode ^
      address.hashCode ^
      choices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuestionPropPub &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subtitle == other.subtitle &&
          index == other.index &&
          address == other.address &&
          choices == other.choices;
}
