// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_voted`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `report`

Future<String> compileElectionDef(
        {required String electionJson, required String seed}) =>
    RustLib.instance.api
        .crateApiVoteCompileElectionDef(electionJson: electionJson, seed: seed);

Future<ElectionPropsPub> parseElection({required String electionJson}) =>
    RustLib.instance.api.crateApiVoteParseElection(electionJson: electionJson);

Future<(String?, int?)> getElectionUrl({required Coin c}) =>
    RustLib.instance.api.crateApiVoteGetElectionUrl(c: c);

Future<ElectionPropsPub> getElection({required Coin c}) =>
    RustLib.instance.api.crateApiVoteGetElection(c: c);

Future<ElectionPropsPub> fetchElection(
        {required String url, required int account, required Coin c}) =>
    RustLib.instance.api
        .crateApiVoteFetchElection(url: url, account: account, c: c);

Future<void> deleteElection({required Coin c}) =>
    RustLib.instance.api.crateApiVoteDeleteElection(c: c);

Future<void> deleteElectionData({int? newAccount, required Coin c}) =>
    RustLib.instance.api
        .crateApiVoteDeleteElectionData(newAccount: newAccount, c: c);

Stream<int> scanVotes({required int idAccount, required Coin c}) =>
    RustLib.instance.api.crateApiVoteScanVotes(idAccount: idAccount, c: c);

Future<void> scanBallots({required int idAccount, required Coin c}) =>
    RustLib.instance.api.crateApiVoteScanBallots(idAccount: idAccount, c: c);

Future<BigInt> getBalance({required int idAccount, required Coin c}) =>
    RustLib.instance.api.crateApiVoteGetBalance(idAccount: idAccount, c: c);

Future<String> vote(
        {required int idAccount,
        required String vote,
        required BigInt amount,
        required Coin c}) =>
    RustLib.instance.api.crateApiVoteVote(
        idAccount: idAccount, vote: vote, amount: amount, c: c);

Future<String> delegate(
        {required int idAccount,
        required String address,
        required BigInt amount,
        required Coin c}) =>
    RustLib.instance.api.crateApiVoteDelegate(
        idAccount: idAccount, address: address, amount: amount, c: c);

Future<String> getElectionAddress({required int idAccount, required Coin c}) =>
    RustLib.instance.api
        .crateApiVoteGetElectionAddress(idAccount: idAccount, c: c);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Context>>
abstract class Context implements RustOpaqueInterface {}

class ElectionPropsPub {
  final int start;
  final int end;
  final bool needSig;
  final String name;
  final List<QuestionProp> questions;
  final String caption;
  final String address;
  final Uint8List domain;

  const ElectionPropsPub({
    required this.start,
    required this.end,
    required this.needSig,
    required this.name,
    required this.questions,
    required this.caption,
    required this.address,
    required this.domain,
  });

  @override
  int get hashCode =>
      start.hashCode ^
      end.hashCode ^
      needSig.hashCode ^
      name.hashCode ^
      questions.hashCode ^
      caption.hashCode ^
      address.hashCode ^
      domain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ElectionPropsPub &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          needSig == other.needSig &&
          name == other.name &&
          questions == other.questions &&
          caption == other.caption &&
          address == other.address &&
          domain == other.domain;
}

class QuestionProp {
  final String title;
  final String subtitle;
  final List<String> answers;

  const QuestionProp({
    required this.title,
    required this.subtitle,
    required this.answers,
  });

  @override
  int get hashCode => title.hashCode ^ subtitle.hashCode ^ answers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuestionProp &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subtitle == other.subtitle &&
          answers == other.answers;
}
