// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'voting_drive.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `account_seed`, `delegation_identity`, `ensure_nonempty`, `fetch_round_timing`, `gather_round_inputs`, `json_unix_seconds`, `prepare_bundles`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GatheredRound`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Prepares one round for submission: persists the bundle layout from the
/// wallet's eligible notes and returns the eligibility preview.
///
/// The explicit user step before `voting_drive_start`: without persisted
/// bundle rows the driver quiesces with `needs_bundle_setup` and nothing can
/// be planned. Safe to repeat; existing bundle rows are reused when they
/// still match the current note set.
Future<VotingEligibilityPreview> votingPrepareRound(
        {required String roundId,
        required String lightwalletdUrl,
        required String roundName,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingDriveVotingPrepareRound(
        roundId: roundId,
        lightwalletdUrl: lightwalletdUrl,
        roundName: roundName,
        c: c);

/// Starts driving one round: delegation (if still owed), vote casting, chain
/// submission, and share handoff.
///
/// Returns false when a run is already live for this wallet and round. The
/// run is idempotent and resumable: every step is planned from durable
/// sidecar state, so restarting after a crash or cancel is always safe.
Future<bool> votingDriveStart(
        {required String roundId,
        required String lightwalletdUrl,
        required String roundName,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingDriveVotingDriveStart(
        roundId: roundId,
        lightwalletdUrl: lightwalletdUrl,
        roundName: roundName,
        c: c);

/// Polls one round's driver run; idle when nothing was started or it finished.
Future<VotingDriveStatus> votingDriveStatus(
        {required String roundId, required Coin c}) =>
    RustLib.instance.api
        .crateApiVotingDriveVotingDriveStatus(roundId: roundId, c: c);

/// Cancels one round's driver run, waking any in-flight retry wait.
Future<bool> votingDriveCancel({required String roundId, required Coin c}) =>
    RustLib.instance.api
        .crateApiVotingDriveVotingDriveCancel(roundId: roundId, c: c);

/// Cancels every live driver run for the current wallet, leaving other
/// wallets untouched. Wallet switch and backgrounding call this so no run
/// outlives its wallet; durable effects stay resumable through a later start.
Future<BigInt> votingDriveCancelAll({required Coin c}) =>
    RustLib.instance.api.crateApiVotingDriveVotingDriveCancelAll(c: c);

/// Snapshot of one round's driver run for the UI.
@freezed
sealed class VotingDriveStatus with _$VotingDriveStatus {
  const factory VotingDriveStatus({
    required String roundId,
    required bool running,
    required BigInt dispatches,
    required int completedProposals,
    required int totalProposals,
    required int remainingObligations,
    String? quiescence,
    required List<String> failures,
  }) = _VotingDriveStatus;
}

/// Eligibility preview for the round's persisted bundle plan.
@freezed
sealed class VotingEligibilityPreview with _$VotingEligibilityPreview {
  const factory VotingEligibilityPreview({
    required int noteCount,
    required BigInt eligibleWeightZatoshi,
    required bool isEligible,
    required BigInt privacyTrimDroppedValueZatoshi,
    required int skippedSuffixBundles,
    required int skippedSuffixNotes,
    required BigInt skippedSuffixValueZatoshi,
  }) = _VotingEligibilityPreview;
}
