// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'voting.dart';
part 'voting_workflow.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `clear_live_progress`, `coin_from_input`, `confirm_and_verify_delegation`, `confirm_vote`, `delegation_recorded_tx`, `draft_proposal_ids`, `drafts_json`, `durare_err`, `ensure_engine`, `inject_vote_round_id`, `is_terminal_status`, `now_epoch_secs`, `parse_submit_response`, `parse_tx_confirmation`, `peek_live_progress`, `poll_delegation_confirmation`, `poll_tx_confirmation`, `progress_event`, `read_stream_events`, `read_workflow_row`, `remaining_label`, `resolve_chain`, `resolve_pir`, `sanitized_commit_drafts`, `set_live_progress`, `submit_and_confirm_vote`, `vote_round`, `wallet_id_of`, `with_height`, `with_tx`, `workflow_status_of`, `write_confirmation`, `write_progress`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DelegationWork`, `ShareTick`, `ShareWork`, `TxConfirmation`, `VoteRoundOutput`, `VoteRound`, `VoteWorkItem`, `WorkflowEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Starts (or attaches to) the durable workflow for a round. Idempotent: when
/// a workflow row already exists for `round_id` it is returned instead of
/// starting a second run (durare would otherwise spawn a concurrent duplicate).
Future<VotingWorkflowStatus> votingWorkflowStart(
        {required VoteRoundInput input, required Coin c}) =>
    RustLib.instance.api
        .crateApiVotingWorkflowVotingWorkflowStart(input: input, c: c);

/// Returns the current durable-workflow status for a round, or `None` when no
/// workflow row exists yet.
Future<VotingWorkflowStatus?> votingWorkflowStatus(
        {required String roundId, required Coin c}) =>
    RustLib.instance.api
        .crateApiVotingWorkflowVotingWorkflowStatus(roundId: roundId, c: c);

/// Clears a failed (terminal-error) workflow row and starts a fresh run from
/// the same input under the same workflow id. The fork's `voting_*` tables
/// are untouched — artifacts persist, so steps skip completed work.
///
/// Foreign keys are disabled on the wallet pool, so the engine's
/// `ON DELETE CASCADE` never fires: the child rows must be deleted manually.
Future<VotingWorkflowStatus> votingWorkflowRetry(
        {required String roundId, required Coin c}) =>
    RustLib.instance.api
        .crateApiVotingWorkflowVotingWorkflowRetry(roundId: roundId, c: c);

/// Everything the durable vote workflow needs to run (and to reconstruct a
/// `Coin` after a restart, since the workflow input is the only durable state
/// the engine keeps besides the fork's `voting_*` tables).
@freezed
sealed class VoteRoundInput with _$VoteRoundInput {
  const factory VoteRoundInput({
    required String roundId,
    required int coin,
    required int account,
    required String dbFilepath,
    required String url,
    required int serverType,
    required int transport,
    required String proxy,
    required String chainUrl,
    required String pirServerUrl,
    VotingPirLayout? pirLayout,
    String? roundParamsJson,
    String? roundName,
    int? maxRealNotesPerBundle,
    String? lightwalletdUrl,
    required String voteNodeUrl,
    required BigInt ceremonyStart,
    BigInt? voteEnd,
    required List<String> shareServerUrls,
    required bool singleShare,
  }) = _VoteRoundInput;
}

/// Polled status of a round's durable workflow, for the Dart monitor.
@freezed
sealed class VotingWorkflowStatus with _$VotingWorkflowStatus {
  const factory VotingWorkflowStatus({
    required String roundId,
    required String status,
    required String stage,
    double? progress,
    String? error,
    String? doneLabel,
    String? txHash,
    BigInt? confirmHeight,
    BigInt? eligibleWeightZatoshi,
  }) = _VotingWorkflowStatus;
}
