// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'voting.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `normalized_status`, `wallet_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Fetches authenticated server rounds and combines them with sidecar state.
/// The returned action is display-only; execution must obtain a fresh resume
/// plan from the voting crate.
Future<List<VotingRoundListItem>> votingRoundList({required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingRoundList(c: c);

@freezed
sealed class VotingProposalListItem with _$VotingProposalListItem {
  const factory VotingProposalListItem({
    required int proposalId,
    required String title,
    required List<String> options,
  }) = _VotingProposalListItem;
}

@freezed
sealed class VotingRoundListItem with _$VotingRoundListItem {
  const factory VotingRoundListItem({
    required String roundId,
    required String title,
    required String status,
    BigInt? snapshotHeight,
    required int bundleCount,
    required String action,
    required List<VotingProposalListItem> proposals,
  }) = _VotingRoundListItem;
}
