// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'voting.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_ballot_round`, `normalized_status`, `voting_network`, `wallet_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Fetches authenticated server rounds and combines them with sidecar state.
/// The returned action is display-only; execution must obtain a fresh resume
/// plan from the voting crate.
Future<List<VotingRoundListItem>> votingRoundList({required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingRoundList(c: c);

/// Loads selections from the wallet's voting sidecar before submission.
Future<List<VotingSelection>> votingLoadSelections(
        {required String roundId, required Coin c}) =>
    RustLib.instance.api
        .crateApiVotingVotingLoadSelections(roundId: roundId, c: c);

/// Saves a selection or skip without submitting a vote.
Future<void> votingSaveSelection(
        {required String roundId,
        required int proposalId,
        required Decision decision,
        required int numOptions,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingSaveSelection(
        roundId: roundId,
        proposalId: proposalId,
        decision: decision,
        numOptions: numOptions,
        c: c);

/// Returns a proposal to unanswered, subject to the voting lifecycle guards.
Future<void> votingClearSelection(
        {required String roundId, required int proposalId, required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingClearSelection(
        roundId: roundId, proposalId: proposalId, c: c);

@freezed
sealed class Decision with _$Decision {
  const Decision._();

  const factory Decision.choice({
    required int choice,
  }) = Decision_Choice;
  const factory Decision.skipped() = Decision_Skipped;
}

@freezed
sealed class VotingProposalListItem with _$VotingProposalListItem {
  const factory VotingProposalListItem({
    required int proposalId,
    required String title,
    required List<String> options,
  }) = _VotingProposalListItem;
}

@freezed
sealed class VotingRoundListItem with _$VotingRoundListItem {
  const factory VotingRoundListItem({
    required String roundId,
    required String title,
    required String status,
    BigInt? snapshotHeight,
    required int bundleCount,
    required String action,
    required List<VotingProposalListItem> proposals,
    required List<String> helperUrls,
    BigInt? voteEndTime,
  }) = _VotingRoundListItem;
}

/// A proposal and its saved decision. Missing entries are unanswered.
@freezed
sealed class VotingSelection with _$VotingSelection {
  const factory VotingSelection({
    required int proposalId,
    required Decision decision,
  }) = _VotingSelection;
}
