// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'voting.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `to_fork`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VotingShareDelivery`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Creates and persists a fresh app-owned voting hotkey (hex stored secret).
Future<String> votingHotkeyCreate({required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingHotkeyCreate(c: c);

/// Returns the persisted voting hotkey stored secret (hex), if any.
Future<String> votingHotkeyGet({required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingHotkeyGet(c: c);

/// Prepares one delegation bundle from the wallet's own Ironwood notes.
///
/// `round_params_json` is the JSON-serialized `VotingRoundParams` from the
/// vote chain. The wallet must be synced through the round snapshot height;
/// witnesses are rooted at the snapshot's Ironwood `nc_root`.
Future<VotingPreparedInfo> delegationPrepare(
        {required String roundParamsJson,
        required String roundName,
        String? sessionJson,
        required int bundleIndex,
        int? maxRealNotesPerBundle,
        required String lightwalletdUrl,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingDelegationPrepare(
        roundParamsJson: roundParamsJson,
        roundName: roundName,
        sessionJson: sessionJson,
        bundleIndex: bundleIndex,
        maxRealNotesPerBundle: maxRealNotesPerBundle,
        lightwalletdUrl: lightwalletdUrl,
        c: c);

/// Builds and persists the governance PCZT setup for a prepared bundle.
Future<VotingDelegationSetup> delegationSetup(
        {required String roundId, required int bundleIndex, required Coin c}) =>
    RustLib.instance.api.crateApiVotingDelegationSetup(
        roundId: roundId, bundleIndex: bundleIndex, c: c);

/// Signs with the wallet seed, proves against the PIR server, and assembles
/// the chain-ready delegation submission for the vote chain.
Future<VotingDelegationSubmission> delegationSignAndSubmit(
        {required String roundId,
        required int bundleIndex,
        required List<int> pcztBytes,
        required VotingPirLayout pirLayout,
        required String pirServerUrl,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingDelegationSignAndSubmit(
        roundId: roundId,
        bundleIndex: bundleIndex,
        pcztBytes: pcztBytes,
        pirLayout: pirLayout,
        pirServerUrl: pirServerUrl,
        c: c);

/// Records a confirmed delegation transaction and persists the bundle's VAN
/// position (required before any vote).
Future<VotingDelegationConfirmation> delegationConfirm(
        {required String roundId,
        required int bundleIndex,
        required String txHash,
        required String eventsJson,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingDelegationConfirm(
        roundId: roundId,
        bundleIndex: bundleIndex,
        txHash: txHash,
        eventsJson: eventsJson,
        c: c);

/// Syncs the vote-authority-note tree and derives this bundle's VAN witness.
Future<VotingVanWitness> votingVanWitness(
        {required String roundId,
        required int bundleIndex,
        required String voteNodeUrl,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingVanWitness(
        roundId: roundId,
        bundleIndex: bundleIndex,
        voteNodeUrl: voteNodeUrl,
        c: c);

/// Commits a batch of vote drafts for one bundle (hotkey-signed).
///
/// Chains the VAN witness derivation internally, so this may be called right
/// after `voting_van_witness` or standalone.
Future<VotingVoteCommitments> votingCommit(
        {required String roundId,
        required int bundleIndex,
        required String draftsJson,
        required String voteNodeUrl,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingCommit(
        roundId: roundId,
        bundleIndex: bundleIndex,
        draftsJson: draftsJson,
        voteNodeUrl: voteNodeUrl,
        c: c);

/// Returns the chain-ready vote submission and helper-share payloads for one
/// committed vote.
Future<VotingVotePayloads> votingPayloads(
        {required String roundId,
        required int bundleIndex,
        required int proposalId,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingPayloads(
        roundId: roundId,
        bundleIndex: bundleIndex,
        proposalId: proposalId,
        c: c);

/// Records successful vote-chain and helper-share submissions for one vote.
Future<void> votingRecordExecution(
        {required String roundId,
        required int bundleIndex,
        required int proposalId,
        required String voteTxHash,
        required BigInt vcTreePosition,
        required String shareDeliveriesJson,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingRecordExecution(
        roundId: roundId,
        bundleIndex: bundleIndex,
        proposalId: proposalId,
        voteTxHash: voteTxHash,
        vcTreePosition: vcTreePosition,
        shareDeliveriesJson: shareDeliveriesJson,
        c: c);

/// Records a confirmed cast-vote transaction.
Future<VotingVoteConfirmation> votingConfirm(
        {required String roundId,
        required int bundleIndex,
        required int proposalId,
        required String txHash,
        required String eventsJson,
        required Coin c}) =>
    RustLib.instance.api.crateApiVotingVotingConfirm(
        roundId: roundId,
        bundleIndex: bundleIndex,
        proposalId: proposalId,
        txHash: txHash,
        eventsJson: eventsJson,
        c: c);

@freezed
sealed class VotingDelegationConfirmation with _$VotingDelegationConfirmation {
  const factory VotingDelegationConfirmation({
    required String txHash,
    required int vanLeafPosition,
  }) = _VotingDelegationConfirmation;
}

@freezed
sealed class VotingDelegationSetup with _$VotingDelegationSetup {
  const factory VotingDelegationSetup({
    required Uint8List pcztBytes,
    required Uint8List pcztSighash,
    required Uint8List rk,
    required int actionIndex,
    required Uint8List actionBytes,
    required Uint8List tx1Effects,
  }) = _VotingDelegationSetup;
}

@freezed
sealed class VotingDelegationSubmission with _$VotingDelegationSubmission {
  const factory VotingDelegationSubmission({
    required Uint8List proof,
    required Uint8List rk,
    required Uint8List nfSigned,
    required Uint8List cmxNew,
    required Uint8List govComm,
    required List<Uint8List> govNullifiers,
    required Uint8List alpha,
    required String voteRoundId,
    required Uint8List spendAuthSig,
    required Uint8List sighash,
    required Uint8List tx1Effects,
  }) = _VotingDelegationSubmission;
}

@freezed
sealed class VotingEncryptedShare with _$VotingEncryptedShare {
  const factory VotingEncryptedShare({
    required Uint8List c1,
    required Uint8List c2,
    required int shareIndex,
  }) = _VotingEncryptedShare;
}

@freezed
sealed class VotingPirLayout with _$VotingPirLayout {
  const factory VotingPirLayout({
    required int pirDepth,
    required int tier0Layers,
    required int tier1Layers,
    required int polyLen,
  }) = _VotingPirLayout;
}

@freezed
sealed class VotingPreparedInfo with _$VotingPreparedInfo {
  const factory VotingPreparedInfo({
    required String roundId,
    required int bundleIndex,
    required BigInt eligibleWeightZatoshi,
    required BigInt delegatedWeightZatoshi,
    required String roundName,
  }) = _VotingPreparedInfo;
}

@freezed
sealed class VotingSharePayload with _$VotingSharePayload {
  const factory VotingSharePayload({
    required Uint8List sharesHash,
    required int proposalId,
    required int voteDecision,
    required VotingEncryptedShare encShare,
    required BigInt treePosition,
    required List<VotingEncryptedShare> allEncShares,
    required List<Uint8List> shareComms,
    required Uint8List primaryBlind,
  }) = _VotingSharePayload;
}

@freezed
sealed class VotingSignedVoteCommitment with _$VotingSignedVoteCommitment {
  const factory VotingSignedVoteCommitment({
    required int proposalId,
    required int choice,
    required String voteRoundId,
    required Uint8List vanNullifier,
    required Uint8List voteAuthorityNoteNew,
    required Uint8List voteCommitment,
    required Uint8List proof,
    required int anchorHeight,
    required Uint8List rVpk,
    required Uint8List voteAuthSig,
    required String commitmentBundleJson,
  }) = _VotingSignedVoteCommitment;
}

@freezed
sealed class VotingVanWitness with _$VotingVanWitness {
  const factory VotingVanWitness({
    required List<Uint8List> authPath,
    required int position,
    required int anchorHeight,
  }) = _VotingVanWitness;
}

@freezed
sealed class VotingVoteCommitments with _$VotingVoteCommitments {
  const factory VotingVoteCommitments({
    required int bundleIndex,
    required List<VotingSignedVoteCommitment> commitments,
  }) = _VotingVoteCommitments;
}

@freezed
sealed class VotingVoteConfirmation with _$VotingVoteConfirmation {
  const factory VotingVoteConfirmation({
    required String txHash,
    required int vanLeafPosition,
    required BigInt vcTreePosition,
  }) = _VotingVoteConfirmation;
}

@freezed
sealed class VotingVotePayloads with _$VotingVotePayloads {
  const factory VotingVotePayloads({
    required VotingVoteSubmission submission,
    required List<VotingSharePayload> sharePayloads,
  }) = _VotingVotePayloads;
}

@freezed
sealed class VotingVoteSubmission with _$VotingVoteSubmission {
  const factory VotingVoteSubmission({
    required String voteRoundId,
    required int proposalId,
    required Uint8List vanNullifier,
    required Uint8List voteAuthorityNoteNew,
    required Uint8List voteCommitment,
    required Uint8List proof,
    required Uint8List rVpk,
    required Uint8List voteAuthSig,
    required int anchorHeight,
  }) = _VotingVoteSubmission;
}
