// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'coin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'zsa.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<List<ZsaHolding>> listZsaHoldings({required Coin c}) =>
    RustLib.instance.api.crateApiZsaListZsaHoldings(c: c);

/// A ZSA token holding representing a balance of a specific asset.
@freezed
sealed class ZsaHolding with _$ZsaHolding {
  const factory ZsaHolding({
    required PlatformInt64 idAsset,
    required Uint8List assetDescHash,
    required String assetName,
    required Uint8List ik,
    required Uint8List assetBase,
    required bool finalized,
    required int firstSeenHeight,
    required BigInt balance,
  }) = _ZsaHolding;
}
