name: "Build Windows"
inputs:
  version:
    required: true
outputs:
  outdir:
    value: ${{ steps.out.outputs.outdir }}
runs:
  using: "composite"
  steps:
    - name: Install Inno-Setup
      shell: powershell
      run: |
        $InnoSetup = Join-Path ${env:PROGRAMFILES(X86)} -ChildPath 'Inno Setup 6\iscc.exe'
        if (!(Test-Path $InnoSetup)) {
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "D:\\is.exe"
          Start-Process -FilePath "D:\\is.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
        }
