name: Build and Release GraphQL Server

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    tags:
      - zkool-v*

jobs:
  zkool-graphql:
    uses: ./.github/workflows/zkool-graphql-build.yml
    with:
      ledger-transport: ledger

  release:
    needs: zkool-graphql
    if: ${{ !startsWith(github.head_ref, 'release-please--branches--') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Restore zkool_graphql
        uses: actions/cache/restore@v5
        with:
          path: target/release/zkool_graphql
          key: ${{ runner.os }}-zkool-graphql-ledger-${{ hashFiles('Cargo.lock', 'rust/Cargo.toml', 'rust/src/**', 'lib/**/*.dart', 'pubspec.yaml', 'pubspec.lock') }}
      - name: Create Release
        if: startsWith(github.ref_name, 'zkool-v')
        uses: softprops/action-gh-release@v3
        with:
          files: ./target/release/zkool_graphql
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
