name: Build Zkool Kiosk ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-kiosk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version number
        id: version
        run: |
          RELEASE_VERSION=$(yq '.version' pubspec.yaml)
          echo "result=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter app (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          flutter build linux --release

      - name: Install Debian live-build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build systemd-sysv debootstrap cage libgtk-3-0 libwayland-client0

      - name: Prepare live-build config
        run: |
          mkdir -p live-build/config/includes.chroot/usr/local/bin
          mkdir -p live-build/config/includes.chroot/etc/systemd/system
          mkdir -p live-build/config/includes.chroot/home/kiosk

          # Copy Flutter build
          cp -r build/linux/x64/release/bundle live-build/config/includes.chroot/opt/zkool

          # Create kiosk startup service
          cat <<'EOF' > live-build/config/includes.chroot/etc/systemd/system/kiosk.service
          [Unit]
          Description=Zkool Kiosk
          After=graphical.target

          [Service]
          User=kiosk
          Environment=GDK_BACKEND=wayland
          ExecStart=/usr/bin/cage /opt/zkool/zkool
          Restart=always

          [Install]
          WantedBy=graphical.target
          EOF

          # Add autologin + user setup
          cat <<'EOF' > live-build/config/includes.chroot/usr/local/bin/setup-kiosk.sh
          #!/bin/bash
          set -e
          useradd -m kiosk || true
          mkdir -p /home/kiosk
          chown -R kiosk:kiosk /home/kiosk
          systemctl enable kiosk.service
          EOF
          chmod +x live-build/config/includes.chroot/usr/local/bin/setup-kiosk.sh

          echo "lb config"
          cat <<'EOF' > live-build/auto/config
          #!/bin/bash
          lb config noauto \
            --architectures amd64 \
            --distribution bookworm \
            --binary-images iso-hybrid \
            --bootappend-live "boot=live config persistence"
          EOF
          chmod +x live-build/auto/config

      - name: Build the ISO
        run: |
          cd live-build
          sudo ./auto/config
          sudo lb build

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: zkool-kiosk-${{ env.RELEASE_VERSION }}.iso
          path: live-build/live-image-amd64.hybrid.iso
