name: Build and Release Linux Debian Package on ARM64

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/${{ github.repository_owner }}/zkool-ci-image:0.0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup PATH
        run: |
          echo "/flutter/bin" >> $GITHUB_PATH
          echo "/root/.pub-cache/bin" >> $GITHUB_PATH
          echo "/root/.cargo/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          cargo version
          fastforge package --platform=linux --targets=deb
        env:
          RUSTUP_HOME: /root/.rustup
      - name: Rename deb package
        id: package
        run: |
          PKG_PATH=$(find dist/ -type f -name '*.deb' | head -n 1)
          echo "Found package: $PKG_PATH"
          mv $PKG_PATH .
          BASENAME=$(basename $PKG_PATH ".deb")
          mv $BASENAME.deb $BASENAME-arm64.deb
          echo "PKG_PATH=$BASENAME-arm64.deb" >> $GITHUB_OUTPUT
      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.package.outputs.PKG_PATH }}
